// Code generated by "stringer -type=FilterResult -linecomment"; DO NOT EDIT.

package permgit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FilterResult_Out-0]
	_ = x[FilterResult_DirDive-1]
	_ = x[FilterResult_In-2]
}

const _FilterResult_name = "OutDirDiveIn"

var _FilterResult_index = [...]uint8{0, 3, 10, 12}

func (i FilterResult) String() string {
	if i >= FilterResult(len(_FilterResult_index)-1) {
		return "FilterResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterResult_name[_FilterResult_index[i]:_FilterResult_index[i+1]]
}
